version: 2.1

orbs:
  node: circleci/node@6.1.0
  python: circleci/python@2.1.1

jobs:
  plan:
    executor: python/default
    steps:
      - checkout
      - python/install-packages: 
          pkg-manager: pip
      - run: 
          name: Plan Module Updates
          command: | 
            python3 scripts/plan.py
      - persist_to_workspace:
          root: ~/project
          paths: 
            - scripts/*.txt
  
  build:
    executor: node/default
    steps:
     - checkout
     - attach_workspace:
        at: .
     - node/install-packages:
        pkg-manager: npm
     - run: 
        command: |
          # sudo npm install uglify-js -g
          node create.js scripts/moduleOutput.txt
      

workflows:
  continuous-integration:
    jobs:
    - plan:
        context: [Github]
    - build:
        requires: [plan]
    # - deploy:
    #   requires:
    #   - build
    #   filters:
    #     branches:
    #       only:
    #       - /main/ 