version: 2.1

orbs:
  node: circleci/node@6.1.0
  python: circleci/python@2.1.1

jobs:
  plan:
    executor: python/default
    steps:
      - checkout
      - run: 
          name: Plan Module Updates
          command: python3 plan.py
      - persist_to_workspace:
          root: workspace # check this to see if you need this
          path: output.txt
  
  build:
  # TODO Implement
    executor: node/default
    steps:
     - run: node create.js workspace/output.txt
      

workflows:
  continuous-integration:
    jobs:
    - plan
    - build:
        requires: [plan]
    # - deploy:
    #   requires:
    #   - build
    #   filters:
    #     branches:
    #       only:
    #       - /main/ 